In [113]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler, StandardScaler

from sklearn.metrics import classification_report, confusion_matrix

import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [114]:
df = pd.read_excel('Stocks Health.xlsx')

In [115]:
df.head()

STOCK  Market Cap  ROE %  Gross Margin %  Operating Margin %  \
0  NVDA     2673.00    123            75.0                62.0   
1  GOOG      921.00     30            58.0                32.0   
2  SHOP       85.64     15            51.0                14.0   
3  TSLA      709.00     21            18.0                 8.7   
4  BABA      196.00      7            39.1                14.7   

   Net Profit Margin %    PE   PEG    PS   CR  LT Debt ($ M)  \
0                 55.0  51.0  2.55  27.7  4.2           9578   
1                 28.0  22.5  1.12   2.8  2.0          25713   
2                  8.0  73.0  3.64  11.1  7.3           1127   
3                  5.7  62.0  3.00   7.4  1.9           6528   
4                  9.9  21.5  1.00   1.4  1.4          23624   

   Free Cash Flow ($ M) Company Score  
0                 27021         Great  
1                 69495         Great  
2                   921          Good  
3                  4357          Good  
4                 20870          Fair

In [116]:
features = ['Market Cap',
             'ROE %',
             'Gross Margin %',
             'Operating Margin %',
             'Net Profit Margin %',
             'PE',
             'PEG',
             'PS',
             'CR',
             'LT Debt ($ M)',
             'Free Cash Flow ($ M)'
            ]

In [117]:
X = df[features]
y = df["Company Score"]

scaler = StandardScaler()
sX = scaler.fit_transform(X)

In [134]:
le = LabelEncoder() #Encoude the "Good, Fair outputs as numbers"
y_encoded = le.fit_transform(y)
X_train, X_test, y_train, y_test = train_test_split(sX, y_encoded, test_size=10, random_state=42)

In [139]:
print (y_test)

[3 1 0 0 2 3 3 0 1 0]


In [140]:
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [141]:
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
# check results
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred)) 

Accuracy: 0.4
[[1 1 0 2]
 [0 0 2 0]
 [0 0 1 0]
 [0 1 0 2]]
              precision    recall  f1-score   support

           0       1.00      0.25      0.40         4
           1       0.00      0.00      0.00         2
           2       0.33      1.00      0.50         1
           3       0.50      0.67      0.57         3

    accuracy                           0.40        10
   macro avg       0.46      0.48      0.37        10
weighted avg       0.58      0.40      0.38        10



In [142]:
# SAVING PART
df.to_excel("Stocks_Health_Clustered.xlsx")

import pickle
pfile = "stockHealth_preTrainedModel.pkl"  

with open(pfile, 'wb') as file:  
    pickle.dump(model, file)

### CHECK A COMPANY

In [146]:
df_test = pd.read_excel("Stocks_Health_Check.xlsx")
# load model from pickle file
with open(pfile, 'rb') as file:  
    pretrained_model = pickle.load(file)
df_test.head()

STOCK  Market Cap  ROE %  Gross Margin %  Operating Margin %  \
0   XYZ         250     -5             -45                 -35   

   Net Profit Margin %  PE  PEG  PS  CR  LT Debt ($ M)  Free Cash Flow ($ M)  
0                   -8   7   50   7   1         100000                  2050

In [147]:
# Apply pre-trained model
y_predict = pretrained_model.predict(df_test[features])
predicted_rankings = le.inverse_transform(y_predict)

C:\Program Files (x86)\python\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


In [148]:
print(predicted_rankings)

['Good']
